version: '3'
services:
  app:
    image: rittu/app:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    #hostname: crm-app
    ports:
      - "8080:80"
    volumes:
      - /opt/Sample-CRM/app:/opt/app
      - /opt/Sample-CRM/nginx/conf/main.conf:/etc/nginx/nginx.conf
      - /opt/Sample-CRM/nginx/conf/app.conf:/etc/nginx/conf.d/app.conf
      - /opt/Sample-CRM/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/Sample-CRM/supervisor/conf/app.ini:/etc/supervisord.d/app.ini
      - /opt/Sample-CRM/supervisor/conf/nginx.ini:/etc/supervisord.d/nginx.ini
    depends_on:
      - redis
    networks:
      - crm-net
    deploy:
      mode: replicated
      replicas: 10
  redis:
    image: sloopstash/redis:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    #hostname: crm-redis
    volumes:
      - /opt/Sample-CRM/redis/data:/opt/redis/data
      - /opt/Sample-CRM/redis/log:/opt/redis/log
      - /opt/Sample-CRM/redis/conf/main.conf:/opt/redis/conf/redis.conf
      - /opt/Sample-CRM/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/Sample-CRM/supervisor/conf/redis.ini:/etc/supervisord.d/redis.ini
    networks:
      - crm-net
networks:
  crm-net:
    external:
      name: crm-net